services:
  # MongoDB
  mongo:
    image: mongo
    container_name: mern-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ISMT
      MONGO_INITDB_ROOT_PASSWORD: ISMT
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Mongo Express
  mongo-express:
    image: mongo-express
    container_name: mern-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://ISMT:ISMT@mongo:27017/schooldb?authSource=admin
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: ISMT
      ME_CONFIG_BASICAUTH_PASSWORD: ISMT
    depends_on:
      - mongo

  # Backend
  backend:
    build: ./backend
    container_name: mern-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://ISMT:ISMT@mongo:27017/schooldb?authSource=admin
      - PORT=5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: ["npm", "run", "dev"]

  # Frontend
  frontend:
    build: ./frontend
    container_name: mern-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  mongo-data:
